south/tai: fix bug when accessing a module which is not created (#131)
It is possible that taish.get_module(key) raises an error when taish
hasn't created a module with the key ( = location ).

```
ERROR:sysrepo:Invalid arguments for function "_sr_un_lock".
INFO:gstai.main:stop server
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gstai/main.py", line 509, in start
    module = await self.taish.get_module(key)
  File "/usr/local/lib/python3.7/dist-packages/taish/__init__.py", line 159, in get_module
    raise Exception("module {} not created yet".format(location))
Exception: module /dev/piu1 not created yet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gssouthd-tai", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gstai/main.py", line 571, in main
    asyncio.run(_main(args.taish_server))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/gstai/main.py", line 551, in _main
    tasks = await server.start()
  File "/usr/local/lib/python3.7/dist-packages/gstai/main.py", line 531, in start
    self.sess.subscribe_oper_data_request('goldstone-tai', '/goldstone-tai:modules/module', self.oper_cb, oper_merge=True, asyncio_register=True)
  File "/usr/local/lib/python3.7/dist-packages/sysrepo/session.py", line 1197, in __exit__
    str2c(self.module_name),
  File "/usr/local/lib/python3.7/dist-packages/sysrepo/errors.py", line 178, in check_call
    raise SysrepoError.new(msg, ret)
sysrepo.errors.SysrepoInvalArgError: Invalid arguments for function "_sr_un_lock".: Invalid argument
```

Signed-off-by: Wataru Ishida <wataru.ishid@gmail.com>