north/snmp: Python3.10 support
TypeError: As of 3.10, the *loop* parameter was removed from Event()
since it is no longer necessary

Signed-off-by: Wataru Ishida <wataru.ishid@gmail.com>